### ISSUE TITLE
Issue de prueba

### ISSUE THREAD

**Issue by JoseManuelBravoDAW** [ajm14/JAVA1_issue#1]
private static boolean deseaContinuar(){
		char caracter;
		//boolean continuar;
		do{
			caracter = Teclado.leerCaracter("Desea continuar?");
		}while (caracter != 's' && caracter != 'S' && caracter != 'n' && caracter != 'N');
		
		if (caracter == 's' || caracter == 'S'){
			//continuar = true;
			return true;
		} else 
			
				return false;
			
		//return continuar;
	}
}

tienes que depurar ese codigo

**Comment by ajm14** [comment]
de acuerdo, gracias

**Comment by JoseManuelBravoDAW** [comment]
De nada
